# Site settings
title: George Lifchits
email: me@georgelifchits.ca
description: >
  Graduate student at University of Toronto, full-stack web developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://georgelifchits.ca" # the base hostname & protocol for your site
github_username:  glifchits

# Build settings
markdown: kramdown
